INSERT INTO "User" (email, name, number, password) VALUES
('jillrhodes@miller.com', 'Allison Hill', '9746317213', 'T$dJL8Ti+a83'),
('smiller@montgomery.com', 'Andrew Stevens', '7478163327', 'ypjGLn0E!dY3'),
('megan03@trujillo.com', 'Joel Nelson', '7107420369', 'Ba3SL76w@VsH'),
('ycarlson@carlson-mcdonald.com', 'Anthony Rodriguez', '8181241943', '(0hix9+!(fVi'),
('amberosborne@hotmail.com', 'Katie Gonzalez', '8051802512', '@u9nA%qp!NKi'),
('jenniferross@santos.com', 'Joseph Obrien', '7958682846', '@SC!e%%#$38k'),
('clintonhopkins@yahoo.com', 'Dana Kennedy', '7599310825', 'O6Z%fl(x&_1M'),
('gabrieltucker@hancock.com', 'Kimberly Smith', '7440213415', '&k9dgiaO20%M'),
('yorkcasey@leonard.biz', 'Thomas Schmidt', '9906402157', '@9JVQH3s5HbA'),
('david51@wood.info', 'Kristine Garcia', '9342331444', 'a!m(bz)(*S4T'),
('waltersmaria@smith.com', 'Deborah Freeman', '7373399426', '#!^RswnV_)7s'),
('sarayoung@gmail.com', 'Brian Deleon', '9536146025', 'gCu#6A7f*qp4'),
('rasmussenjoshua@hotmail.com', 'Matthew Ross', '8812140441', 'C(q6UyVWDrKy'),
('ryan59@alvarado-martinez.com', 'Michael Smith', '7136505587', 'CdTVbGn0U(4A'),
('donnacampbell@hotmail.com', 'Jeremy Lowe', '7127978094', 'mhb92@Kco^I_'),
('zrobinson@holmes.com', 'Charles Watts', '7402418010', 'bzW2ZXfonS*h'),
('scott43@rogers-orozco.com', 'Richard Washington', '7939042955', '#e%ISIHms2dp'),
('tracynelson@yahoo.com', 'Elizabeth Price', '7999270936', '!H6MKY@vT#Z_'),
('karen64@gmail.com', 'Daniel Murphy', '9170484433', '$*40w##roX5N'),
('tamirodriguez@hickman.biz', 'Pamela Jackson', '9585650756', '3Y*jos(y&DCF'),
('bzimmerman@gmail.com', 'Samantha Garcia', '7113971123', 'XujMnUi6v+8h'),
('lauren54@haynes.com', 'Samuel White', '9410529190', 'OidZOXn4@AV3'),
('jerry35@gmail.com', 'Heather Chavez', '7854001193', '84YfwQ8*+41@'),
('agarcia@mitchell.com', 'Kristen Terry', '9791232393', 'H^Y7+TDc%iWk'),
('ashley09@hotmail.com', 'Elizabeth Chapman', '9340505846', '7@5UgIdM#93p'),
('owilson@hernandez.com', 'Lori Guerrero', '8801823908', '#xKMTH8RK4rg'),
('barbara27@pearson.org', 'Michael Valencia', '7946785248', 'D7bpCCpv&SLB'),
('hbrown@yahoo.com', 'April Booth', '8929338154', 'i7SUKdoy)5+S'),
('scantu@thornton.info', 'Susan Murray MD', '9530876844', 'GuPrR8kev$78'),
('ugibson@gmail.com', 'Jill Washington', '8194819984', '5m$heSGb+3O#'),
('bowenrobert@hotmail.com', 'Jessica Fox', '7027911967', '#zdPpppGB1iq'),
('wgood@padilla.com', 'Tammie Bright', '7685731524', '%E0KIc1zX!cO'),
('erica21@yahoo.com', 'Julia Estrada', '9998485882', '^dLAJpuGE99@'),
('swall@lawson.com', 'Melissa Garner', '8815115025', 'cfao3TiAKUg_'),
('maria47@yahoo.com', 'Carlos Ryan', '8461364854', 'M+h4cZHdT&57'),
('leonardthomas@hotmail.com', 'Deborah James', '8193448329', 'ZZMda5Thz((R'),
('fpena@russell.com', 'Melissa Fernandez', '7667779376', '$*cSyhH2)7Ob'),
('brendali@murphy.org', 'Cameron Cunningham', '7924765563', 'R!(q)Eke@7)4'),
('stephen00@boone-simmons.com', 'Ashley Gordon', '8445662585', 'B7)YVeGW*PCc'),
('maria66@hotmail.com', 'Jessica Beasley', '7438989805', 'b5+u%k&*@mNV'),
('schmittcaroline@yahoo.com', 'Shane Pugh', '7398340369', '9NoDT(84@gQY'),
('jacqueline45@smith-kane.org', 'Sandra Adams', '8631775357', '_xCRFL+BC6er'),
('wnelson@hotmail.com', 'Jeremy Coleman', '7415393687', '@5Ob$NWdA3_6'),
('charles06@stevens.com', 'Casey James', '8541804686', 'em(@ClSn)6o6'),
('charlesschultz@hotmail.com', 'Eric Morgan', '8477278577', 'DwZ_*Y0li(3Y'),
('tramos@vargas-bell.com', 'Lori Hernandez', '9592983555', '%n^OpbPMT%7L'),
('shepherdmary@hotmail.com', 'Kathryn Rosario', '8136108454', '#8zQXftG@cUY'),
('christopher25@ponce-hale.biz', 'David York', '7186618211', 'AF#9WcgcQZJE'),
('chrisrichard@romero.net', 'Ralph Lee', '8973214822', ')F0!Yl0tIc55'),
('michealvalentine@yahoo.com', 'Emily Stokes', '9303082117', 'P*42Yq$mFveQ'),
('bwilkerson@brown-shaw.com', 'Brittany Kim', '7536124280', '&1oLh_9nd_eL'),
('parsonsjohn@gmail.com', 'Kimberly Acosta', '8625792787', 'k!3sW@u5_JN5'),
('cmarks@hughes.com', 'Heather Ashley', '7338444264', 'a@5h)EDxncyH'),
('sarah86@kennedy.com', 'Dakota Moody', '9370996465', '8^KHKwU1dkk0'),
('kirk96@gmail.com', 'Catherine Carter MD', '8259191105', '+qLz8yw^Z7oc'),
('patrick90@hotmail.com', 'Amanda Jones', '9699987374', 'K^_#L8xl1Qt7'),
('melissahayes@wallace.com', 'Donna Hendricks DDS', '9656522106', '_9A+eW0c5yk5'),
('jonesraymond@higgins.org', 'Julie Bird', '8553210608', '^M2)KuVi@Pqn'),
('kingcynthia@hotmail.com', 'Courtney Meza', '9479708607', '%2ZVU0YsCjUp'),
('ismall@may-turner.com', 'Daniel Armstrong', '7825873196', '^6KJ3oBf_py)'),
('robertspatrick@barnes.com', 'Derek Wright', '7298737106', '+zMrG&Hy5)58'),
('kathryn50@yahoo.com', 'Sarah Jordan', '7196814233', 'E99RSgYX!*Fz'),
('jenniferbrock@bryant.com', 'Jennifer Williams', '9840104345', 'zgACmReAm)5F'),
('silvageorge@griffith.com', 'John Coffey', '7978815630', '2KII3WXd!f9Q'),
('erica49@yahoo.com', 'Emily Thompson', '8242911821', 'AvyjedrN$3I9'),
('bobby15@douglas-burgess.com', 'Jennifer Reed', '7342703921', '$_IV5brZ8If*'),
('manuel01@andrews.com', 'Shirley Alvarez', '7999829240', 'zHFvxuqb#*69'),
('francisco74@lopez.org', 'Julie Lee', '7433797840', 'psnQFt1_B_73'),
('contrerassteven@sullivan.com', 'Deborah Ward', '8632629719', 'FjwULzFdt+1n'),
('poolerebecca@armstrong.com', 'Kelsey Cox', '8193887545', '^fOsO%dITTb8'),
('michaelcesar@johnson-ortiz.com', 'Benjamin Henderson', '8947382419', '_tF6Lq)m(zH)'),
('stevenmoore@pineda.com', 'Kimberly Patel', '9730243887', '!rT%yLbq6$KR'),
('kevinthomas@hotmail.com', 'Thomas Johnston', '8566942273', '8T(gNcj$DZG3'),
('meredith27@hart.net', 'Paul Wells', '7698594025', '6C^LFRn$(2Mh'),
('lewisjames@hotmail.com', 'Daniel Meadows', '8589915144', 'W3t@jHRw7PO7'),
('allentran@riley.com', 'Jason Hart', '8525876051', 'Oa67mxZh$kSf'),
('duranrobert@hall.net', 'Kelly Combs', '7899825838', 'Zv*a@Rt@fR5B'),
('lisa46@watson.info', 'Brent Hernandez', '9878380452', 'An^zaWhFN)3&'),
('jasonparrish@alvarez.com', 'Valerie Jacobson', '8146660997', '1o@3_Vbu(T9o'),
('brian63@peterson.org', 'Brenda Hinton', '9935814872', '8&5EAJua&Xle'),
('daniel04@yahoo.com', 'Madison Singh', '9783290795', '&4Te*&TW^p!D'),
('kevin72@jackson.biz', 'Carolyn James', '7306671447', 'EvfOX7ZcHo%p'),
('zedwards@carter-neal.info', 'Brandy Flores', '9616197747', '8)FuKzmi@fv3'),
('jennifermccormick@gmail.com', 'Brenda Turner', '9727210979', 'HPPdSsEsR*9i'),
('tammy61@gmail.com', 'William Byrd', '7735034881', 'h@44Fqcd+zNH'),
('thomas77@yahoo.com', 'Jesse Clark', '9294113287', '@@B(luzQSC4M'),
('nsmith@gmail.com', 'Sonya Cole', '8051454923', 'lR12(SOdB%H('),
('lawrenceallen@white.com', 'Michele Evans', '7701808367', '(G6ZdNztO_BL'),
('acohen@hotmail.com', 'James Hoffman', '8985392498', '7k4#FcjT*OPU'),
('fitzgeralddesiree@gmail.com', 'Jessica Robinson', '8629748727', '%mOij5lVD0Y0'),
('keith48@hotmail.com', 'Douglas Ryan', '8159417075', 'I%8a2)Yz6o@_'),
('heather57@yahoo.com', 'Robert Mack', '9748778024', 'o&xYAykH^9OB'),
('garciakristen@smith-noble.com', 'Samuel Kramer', '9955633092', '2c)aAvna6F*7'),
('lewischristian@perez.com', 'Cynthia Rios', '9392080953', 'e6&l*FAG@WZc'),
('samanthajensen@heath-miller.com', 'Carly Bell', '7943239974', 'GxBSx&SW#j1o'),
('troyrodriguez@little-jones.com', 'Chelsea Myers', '9940395823', 'pUFcEwm@^75%'),
('davidsonamanda@gmail.com', 'Pamela Henderson', '8392783743', '%1lJGYcc%dgo'),
('smithderrick@martin.net', 'Logan Brown', '7240251661', '4j7rjFll(eU^'),
('joycesmith@sanchez.com', 'Mr. Jacob Scott Jr.', '7983753977', '2tFbBIf8&FPs'),
('mark87@gmail.com', 'Andrea Marshall', '7137869475', '^g5Jxsjg3k+u');

INSERT INTO "Merchant" (email, name, auth_type) VALUES
('usweeney@garcia-moreno.com', 'Franco, Wiley and Tapia', 'Github'),
('christopher38@haynes-watson.com', 'Vasquez-Brown', 'Github'),
('grahamtamara@carter.biz', 'Davis, Anderson and Wilkins', 'Github'),
('hardingderek@rodriguez.com', 'Decker, Nguyen and Chavez', 'Google'),
('qparker@davis.com', 'Martinez-Howard', 'Google'),
('christopherwright@yahoo.com', 'Terry, Williams and Huff', 'Github'),
('anthonysullivan@yahoo.com', 'Palmer-Byrd', 'Google'),
('smithmaria@anderson.com', 'Adkins, Wright and Murray', 'Github'),
('johnsoncaleb@hotmail.com', 'Mccoy, Newman and Aguilar', 'Github'),
('williamssteven@gmail.com', 'Lamb-Davis', 'Github'),
('nthompson@gmail.com', 'Hamilton, Ramsey and Crawford', 'Google'),
('deborahporter@mendoza.biz', 'Ramirez-Stephenson', 'Github'),
('mayokimberly@castillo-harrington.com', 'Day PLC', 'Google'),
('anthonycochran@yahoo.com', 'Shaw, Price and White', 'Google'),
('terrigarcia@hotmail.com', 'Stokes Group', 'Github'),
('barbaramcgrath@kelly-combs.com', 'Adams Ltd', 'Github'),
('warnermichael@hotmail.com', 'Young LLC', 'Github'),
('gregory01@gmail.com', 'Thomas, Vaughan and Copeland', 'Github'),
('riverachristina@gmail.com', 'Guzman Inc', 'Google'),
('johnsonbrenda@gmail.com', 'Love-Sellers', 'Google'),
('janet69@rogers.com', 'Mathis LLC', 'Github'),
('grant89@yahoo.com', 'Oconnor Group', 'Google'),
('jessica42@gmail.com', 'Wade and Sons', 'Google'),
('carriemccall@walker.com', 'Smith, Miles and Berry', 'Google'),
('daisymccarty@hotmail.com', 'Mcgee-Young', 'Google'),
('johnjones@yahoo.com', 'Fowler, Tanner and Griffin', 'Google'),
('koconnor@yahoo.com', 'Le Inc', 'Github'),
('poolekristina@hotmail.com', 'Macias-Bell', 'Google'),
('andrew41@peterson.com', 'Chang, Perez and Hayes', 'Github'),
('bbush@hotmail.com', 'Jones, Mcmahon and Spence', 'Github'),
('garciajamie@ortiz.net', 'Lawson Group', 'Github'),
('longandrea@hernandez-ward.biz', 'Guerrero-Evans', 'Github'),
('collinclark@hotmail.com', 'Phillips Ltd', 'Google'),
('kristen77@baker.com', 'Rowland-Wells', 'Google'),
('omarshall@yahoo.com', 'Wood-Griffin', 'Github'),
('lindsey69@spencer.net', 'Brown, Goodwin and Contreras', 'Github'),
('thomasmiller@hotmail.com', 'Sheppard-Mcdaniel', 'Google'),
('averyshane@stanton.com', 'Shaw PLC', 'Github'),
('wendyburton@hotmail.com', 'Henderson Ltd', 'Github'),
('hughesray@gates-stone.com', 'Flores-Acosta', 'Google'),
('eddiematthews@gmail.com', 'Dean, Mills and Barnes', 'Github'),
('natalie46@hotmail.com', 'Hart Inc', 'Google'),
('richard99@steele.com', 'Armstrong-Kennedy', 'Github'),
('morganlaura@yahoo.com', 'Young, Reese and Mccall', 'Google'),
('dennismccann@schroeder-flores.biz', 'Cameron-Garrison', 'Google'),
('xmalone@gmail.com', 'Brewer, Lopez and Lewis', 'Github'),
('kimberlywarren@hotmail.com', 'Moody, Jones and Mckinney', 'Google'),
('antoniowilliams@bush-hill.info', 'Thompson and Sons', 'Google'),
('tracy72@matthews-bailey.com', 'Sanders, Leblanc and Maldonado', 'Github'),
('hughesfrank@hotmail.com', 'Curry-Barker', 'Google'),
('josephortiz@hancock.com', 'Vincent Ltd', 'Google'),
('johnnytrujillo@marquez-fletcher.com', 'Buck-Holland', 'Github'),
('jeffery48@hotmail.com', 'Woodard-York', 'Github'),
('kenneth17@gmail.com', 'Silva-Smith', 'Google'),
('diana43@gmail.com', 'Mcneil-Davidson', 'Google'),
('erin07@yahoo.com', 'Cannon, Yoder and Trujillo', 'Github'),
('matthewreeves@nichols.com', 'Meadows-Sullivan', 'Github'),
('connor24@stokes.com', 'Evans, Jackson and Sandoval', 'Google'),
('vfrench@yahoo.com', 'Davis, Kelly and Garner', 'Google'),
('obrown@carpenter.com', 'Richards-Ford', 'Google'),
('pittsedward@gmail.com', 'Wilson, Becker and Moreno', 'Google'),
('lesliebaldwin@gmail.com', 'Ortiz-Hudson', 'Google'),
('smithjoshua@gmail.com', 'Cook-Hatfield', 'Github'),
('christinaschultz@patterson-woods.com', 'Duran, Burns and Gallagher', 'Google'),
('mcclainkatherine@hotmail.com', 'Ferguson Ltd', 'Google'),
('heathercooper@garcia.org', 'Smith Inc', 'Google'),
('stephen89@hotmail.com', 'Jackson-Colon', 'Github'),
('wendy75@martin.com', 'Hamilton-Mcdaniel', 'Google'),
('lawrencegary@dawson-conner.biz', 'Walker and Sons', 'Github'),
('valdezandrew@wilson.com', 'Scott, Nichols and Williams', 'Github'),
('robert18@dean-haynes.biz', 'Miles-Harris', 'Google'),
('daniel17@lynch.net', 'Hunt PLC', 'Google'),
('benjamincrawford@gmail.com', 'Howard Group', 'Github'),
('conleyelizabeth@herring.com', 'Fitzpatrick, Rivera and Smith', 'Github'),
('joseph01@gmail.com', 'Cummings, Conway and Newman', 'Github'),
('grodgers@gmail.com', 'Phelps LLC', 'Github'),
('michael79@johns-davis.com', 'Christian Ltd', 'Github'),
('mary76@hotmail.com', 'Wilson Group', 'Google'),
('dalepruitt@pham-gregory.com', 'Wilson Ltd', 'Google'),
('hknapp@alexander-brown.com', 'James, Howard and Johnson', 'Google'),
('april91@stanley-wright.com', 'Bush Ltd', 'Google'),
('schneidereric@christian-booth.com', 'Rhodes, Cruz and Combs', 'Github'),
('hunterandrea@yahoo.com', 'Flores-Rivera', 'Google'),
('fmiller@yahoo.com', 'Montoya-Miller', 'Google'),
('powellbarry@smith.org', 'Wilson-Jimenez', 'Google'),
('michael03@yahoo.com', 'Torres, Romero and Clark', 'Google'),
('jennifer11@hotmail.com', 'Castro-Harvey', 'Google'),
('jacqueline02@yahoo.com', 'Smith LLC', 'Google'),
('kingjames@gmail.com', 'Underwood Ltd', 'Google'),
('daniel60@monroe.info', 'Lewis-Summers', 'Google'),
('vsmith@tran.org', 'Barrett-Blanchard', 'Google'),
('jessicaanderson@sandoval-obrien.com', 'Glass-Norman', 'Github'),
('raymond54@ballard-taylor.org', 'Keith, Barnes and Lynch', 'Google'),
('jamesweber@yahoo.com', 'Tanner, Hunt and Cameron', 'Google'),
('jennifer58@aguilar-bender.biz', 'Reed, Chambers and Zavala', 'Github'),
('millsanthony@gmail.com', 'Adkins, Skinner and Mitchell', 'Github'),
('tonyavega@gmail.com', 'Santiago and Sons', 'Google'),
('howardshaun@parrish.net', 'Vaughn LLC', 'Google'),
('housepaul@hotmail.com', 'Young-Mueller', 'Github'),
('christinenorman@yahoo.com', 'Church-Brown', 'Google');